### PR TITLE
Rs add result colors

### LINKED ISSUE #77: add colors when correct / incorrect answer
When an answer is correct or incorrect not only the background should change color, but also the:

### Requirement(s):
- [ ] Button
- [ ] Progress bar
- [ ] Close button

### PR DESCRIPTION
**Pull request by roelandvs**
closes #77

### CODE REVIEW

**Comment by MarvinMichel** [comment]
#### 📝Changed routes:


| [**/**](https://prapla-8jimefl7t-marvinmichel.vercel.app/) |
|:-:|
|<a href="https://prapla-8jimefl7t-marvinmichel.vercel.app/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/-LNlieXMpIwExWF0ZJSXyrLoCfcmqlVGU2_ipsRCoPX2kDaZVOqX35wUIzS-1Ze1YUHhgVm7Ubkz4NEGx4nB_A.png">(view full size)</a> |







Commit f2b801fb0f395d5f550a26541ff7ef6bad82f36a (https://prapla-8jimefl7t-marvinmichel.vercel.app).

File: components/ProgressBar.vue [hunk 1]
```diff
@@ -29,7 +29,7 @@ export default {
 	progress[value]::-webkit-progress-value {
 		background-color: var(--cl-primary-200);
 		min-width: 20px;
-		transition: all 750ms ease-in-out;
+		transition: width 750ms ease-in-out;
```
Comment (MarvinMichel) [inline components/ProgressBar.vue:32]: Transitioning the width can be costful. Using `transform: scaleX(..)` and transitioning the transform would be a better solution

**Review by MarvinMichel — CHANGES_REQUESTED** [review]

**Review by MarvinMichel — APPROVED** [review]

**Review by Vincentvanleeuwen — APPROVED** [review]
